FROM centos:7
RUN yum update & yum -y install centos-release-openstack-queens
RUN sed -i -e "s/enabled=1/enabled=0/g" /etc/yum.repos.d/CentOS-OpenStack-queens.repo
RUN yum --enablerepo=centos-openstack-queens -y install mariadb-server
RUN yum --enablerepo=epel -y install rabbitmq-server memcached
